### ISSUE TITLE
BIMtoOSMParserTest failing on JOSM ci

### ISSUE THREAD

**Issue by don-vip** [JOSM/indoorhelper#9]
BIMtoOSMParserTest is failing for some time on JOSM Jenkins but I don't understand what's wrong:
https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/lastCompletedBuild/jdk=JDK8/testReport/io.parser/BIMtoOSMParserTest/testParse/
```
AssertionFailedError: /var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/test/data/test1_IFC2X3_TC1.ifc ==> expected: <true> but was: <false>
	at io.parser.BIMtoOSMParserTest.assertParseTrue(BIMtoOSMParserTest.java:62)
	at io.parser.BIMtoOSMParserTest.testParse(BIMtoOSMParserTest.java:35)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:777)
```

**Comment by rebeccasc** [comment]
I guess this is because I accidentally enabled the `JOSMTestRules` in https://github.com/JOSM/indoorhelper/blob/fe3d497836a6eb73a90c0e92549edadd0d7c3420/test/unit/io/parser/BIMtoOSMParserTest.java#L24

At the moment I'm not quite sure why this is causing an error... I commented it out again in the later commits. After the next Jenkins build we can have a look if it works again.

**Comment by rebeccasc** [comment]
The following error got fixed with disabling `JOSMTestRules` like described above:
```
AssertionFailedError: /var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/test/data/test1_IFC2X3_TC1.ifc ==> expected: <true> but was: <false>
	at io.parser.BIMtoOSMParserTest.assertParseTrue(BIMtoOSMParserTest.java:62)
	at io.parser.BIMtoOSMParserTest.testParse(BIMtoOSMParserTest.java:35)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:777)
```
But the test actually fails since Jenkins build [JOSM-Plugins/1965/](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/1965/) because of some ant issues:

```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at io.parser.BIMtoOSMParserTest.testParse(BIMtoOSMParserTest.java:43)
	at org.apache.tools.ant.taskdefs.optional.junitlauncher.LauncherSupport.launch(LauncherSupport.java:141)
	at org.apache.tools.ant.taskdefs.optional.junitlauncher.StandaloneLauncher.main(StandaloneLauncher.java:114)
```

The last successful Jenkins build was [JOSM-Plugins/1949/](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/1949/). As far as I can see, there is no change on the indoorhelper between build [JOSM-Plugins/1949/](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/1949/) and [JOSM-Plugins/1965/](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/1965/).

@don-vip Do you have an idea why the ant build fails?

**Comment by don-vip** [comment]
> @don-vip Do you have an idea why the ant build fails?

Right now, none. I changed a lot of things recently for the JUnit 5 migration, performed system updates, etc. This could be a side effect but I don't understand if it's the case.

**Comment by don-vip** [comment]
Ah maybe just a configuration problem:
```
[junitlauncher] 2020-12-14 10:34:11.803 SEVERE: /var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/test/data/test1_IFC2X3_TC1.ifc (No such file or directory)
[junitlauncher] 2020-12-14 10:34:11.793 INFO: io.parser.BIMtoOSMParser-ConfigurationReport: solution set to BOUNDING_BOX
[junitlauncher] 2020-12-14 10:34:11.812 SEVERE: Could not load IFC file.
[junitlauncher] 2020-12-14 10:34:11.794 INFO: io.parser.BIMtoOSMParser-ConfigurationReport: optimizeInputFile enabled; RemoveBlockCommands enabled
[junitlauncher] IFC schema is no supported.
[junitlauncher] 2020-12-14 10:34:11.795 INFO: io.parser.BIMtoOSMParser-ConfigurationReport: optimizeOutput enabled; MergeCloseNodes enabled; MergeDistance set to 0.010000
[junitlauncher] 2020-12-14 10:34:11.813 INFO: io.parser.BIMtoOSMParser: /var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/test/data/test1_IFC2X3_TC1.ifc loading failed
```

**Comment by don-vip** [comment]
@rebeccasc I think it should fix the problem. Let's check tomorrow.

**Comment by don-vip** [comment]
@rebeccasc the error changed, do you see what's wrong?
```
java.lang.NullPointerException
	at nl.tue.buildingsmart.express.population.Part21Parser.simple_entity_instance(Part21Parser.java:381)
	at nl.tue.buildingsmart.express.population.Part21Parser.entity_instance(Part21Parser.java:358)
	at nl.tue.buildingsmart.express.population.Part21Parser.entity_instance_list(Part21Parser.java:343)
	at nl.tue.buildingsmart.express.population.Part21Parser.data_section(Part21Parser.java:338)
	at nl.tue.buildingsmart.express.population.Part21Parser.exchange_file(Part21Parser.java:130)
	at nl.tue.buildingsmart.express.population.Part21Parser.syntax(Part21Parser.java:538)
	at nl.tue.buildingsmart.express.population.ModelPopulation.load(ModelPopulation.java:73)
	at io.parser.BIMtoOSMParser.loadFile(BIMtoOSMParser.java:219)
	at io.parser.BIMtoOSMParser.parse(BIMtoOSMParser.java:154)
	at io.parser.BIMtoOSMParserTest.assertParseTrue(BIMtoOSMParserTest.java:59)
	at io.parser.BIMtoOSMParserTest.testParse(BIMtoOSMParserTest.java:32)
	at org.apache.tools.ant.taskdefs.optional.junitlauncher.LauncherSupport.launch(LauncherSupport.java:141)
	at org.apache.tools.ant.taskdefs.optional.junitlauncher.StandaloneLauncher.main(StandaloneLauncher.java:114)
```

**Comment by rebeccasc** [comment]
> @rebeccasc the error changed, do you see what's wrong?
> 

Not really... In b5db9a3 I tried to disable the only test that's throwing some exception. This doesn't change anything. In 2573604 I disabled the pre-optimization of `.ifc` files. I assume this causes the error. The optimization removes block comments and keeps the result in a temporary file which will be used by `nl.tue.buildingsmart.express.population.ModelPopulation.load`. I am not quite familiar with Jenkins ... this might be a problem. 
After the next build we'll see if this changes something.

If this doesn't work, in fe3d497 I changed the test data path from `test/resources` to `rest/data`. Maybe this broke something and the files cannot be found anymore.
